# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06e249b949b86a7e380a9f5d396d5fa2bf30adbea6fc53154373f8bcd4f68311d2d5d42a964bef288fa37540341417788c4e9cad47811f57611ccecf49d8c06c

test:
  secret_key_base: 25f8a9714b121b16b5473824d141d55353904d7310652d78bb34e491d8f5d5084120c3ba54f0326059b6b5316c6c6dcd4229b7e2a5b4b4e06f4c2f9d71020320

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
